/** Nest DI tokens for the auth HTTP module (patient-web sign-in/sign-up). */
export const DATABASE_POOL = "NELYO_AUTH_DATABASE_POOL";
export const IDENTITY_SESSION_PORTS = "NELYO_IDENTITY_SESSION_PORTS";
export const PASSWORD_CREDENTIAL_PORTS = "NELYO_PASSWORD_CREDENTIAL_PORTS";
export const REGISTRATION_PORTS = "NELYO_REGISTRATION_PORTS";
export const ACTING_CONTEXT_PORTS = "NELYO_AUTH_ACTING_CONTEXT_PORTS";
