export const contentFamilies = [
  "foundation",
  "registration",
  "authentication",
  "patient-onboarding",
  "family-guardian",
  "diaspora-sponsorship",
  "appointment-booking",
  "payment",
  "consultation",
  "pharmacy-matching",
  "laboratory-matching",
  "provider-disclosure",
  "emergency-escalation",
  "accessibility",
  "marketing",
  "marketing-home",
  "marketing-how-it-works",
  "marketing-segment-patients",
  "marketing-segment-family-diaspora",
  "marketing-segment-doctors",
  "marketing-segment-pharmacies",
  "marketing-segment-laboratories",
  "marketing-segment-employers",
  "marketing-segment-hmos",
  "marketing-segment-hospitals",
  "marketing-segment-home-care",
  "marketing-segment-medical-records",
  "marketing-trust-and-safety",
  "marketing-privacy-overview",
  "marketing-accessibility",
  "marketing-faq",
  "marketing-contact",
  "marketing-legal",
  "marketing-emergency",
  "marketing-cta",
  "marketing-microcopy",
  "marketing-seo",
  "marketing-error-pages",
  "marketing-cookie-consent",
  "marketing-footer-pages",
  "marketing-footer",
  "marketing-help-widget",
  "marketing-nav",
  "marketing-family-health",
  "auth-signin",
  "auth-create-account",
  "auth-forgot-password",
  "auth-reset-password",
  "account"
] as const;
export type ContentFamily = (typeof contentFamilies)[number];
export type ContentId = string;
export const makeContentId = <T extends ContentFamily>(family: T, slug: string): ContentId => {
  if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)) throw new Error("Invalid content slug: " + slug);
  return family + "." + slug;
};
